---
- name: Install Pre-Requisites
  become: yes
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - zsh
      - vim
      - python3-pip
      - bpytop
      - htop
      - ripgrep
      - iftop
      - curl
      - vlc
      - wireguard-tools
      - resolvconf
      - simplescreenrecorder
      - tree
      - gimp
      - zip
      - unzip
      - rar
      - unrar
      - gnome-tweaks
      - gnome-shell-extension-manager
      - qbittorrent
      - filezilla
      - firejail
      - bat
      - chromium-browser
      - fd-find

- name: Create a symbolic link for bat
  become: yes
  file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
